<?php

class GBF_ACF{
    public function __construct(){

        //add_filter('acf/load_field/name=form_id', array($this, 'acf_load_form_field_choices'));

        // When including the PRO plugin, hide the ACF Updates menu
        add_filter('acf/settings/show_updates', '__return_false', 100);        
    }

    public function gen_options_page() {        
        if( function_exists('acf_add_options_page') ) {    
            acf_add_options_page(array(
                'page_title'    => 'BaseCamp Link',
                'menu_title'    => 'BaseCamp Link',
                'menu_slug'     => 'base-camp-link',
                'capability'    => 'manage_options',
                'redirect'      => false
            ));
        }
        else{
            add_options_page( 'BaseCamp Link', 'BaseCamp Link', 'manage_options', 'base-camp-link', array($this, 'my_plugin_options'));
        }
    }
    public function gen_options_fields(){
        if ( function_exists('acf_add_local_field_group') ):

            acf_add_local_field_group(array(
                'key' => 'group_630e71fee0e2f',
                'title' => 'BaseCamp Link',
                'fields' => array(
                    array(
                        'key' => 'field_6483895a1eaac',
                        'label' => 'Client ID',
                        'name' => 'client_id',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_save_meta' => 0,
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6483896b1eaad',
                        'label' => 'Client Secret',
                        'name' => 'client_secret',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_save_meta' => 0,
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_630e7238af028',
                        'label' => 'Endpoint URL',
                        'name' => 'endpoint_url',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="'.get_site_url().'/wp-json/gbf/v1/auth">Authorize</a> <br> <a href="https://launchpad.37signals.com/authorization/new">Refresh Token</a> <br> Endpoint URL Example: https://3.basecampapi.com/$ACCOUNT_ID/buckets/$bucket_ID/todolists/$todolist_ID/',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_630e7393af02b',
                        'label' => 'Form ID to Watch',
                        'name' => 'form_id',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => 'Contact Us',
                            3 => 'Website Projects Form',
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                        'allow_custom' => 0,
                        'search_placeholder' => '',
                    ),
                    array(
                        'key' => 'field_630e72abaf029',
                        'label' => 'Fields to Send',
                        'name' => 'fields_to_send',
                        'aria-label' => '',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_repeater_stylised_button' => 0,
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => 'Add Row',
                        'rows_per_page' => 20,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_630e7f678a294',
                                'label' => 'Form Field ID',
                                'name' => 'form_field_id',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    3 => 'Name',
                                    14 => 'Email',
                                    4 => 'Today\'s Date',
                                    5 => 'Date Needed',
                                    6 => 'Is this needed for a meeting? If so what is the meeting date?',
                                    8 => 'Advertiser name',
                                    7 => 'What is this project for? (Choose from dropdown)',
                                    36 => '',
                                    32 => 'Company',
                                    35 => 'HTML Block',
                                    34 => 'Add New Company',
                                    17 => 'When should this listing expire?',
                                    28 => 'HTML Block',
                                    47 => 'Company Information',
                                    60 => 'Stacked or Square Logo',
                                    61 => 'Horizontal Logo',
                                    39 => 'Company Address',
                                    40 => 'Company Phone Number',
                                    41 => 'Company Email',
                                    42 => 'Company Website',
                                    43 => 'Company Social Media Links',
                                    44 => 'Company Description (1-2 paragraphs)',
                                    46 => 'Job Listing Information',
                                    48 => 'Job Title (up to two)',
                                    54 => 'Job Type',
                                    51 => 'Salary or Hourly Rate',
                                    62 => 'Job Category(ies)',
                                    63 => 'Other Job Category(ies)',
                                    52 => 'Job Description(s) (up to 2 positions)',
                                    53 => 'Qualifications',
                                    55 => 'Job Responsibilities',
                                    56 => 'Compensations and Benefits',
                                    57 => 'More Information',
                                    58 => 'How to Apply',
                                    59 => 'Job Location',
                                    37 => '',
                                    31 => 'Pixel Placement Information',
                                    38 => '',
                                    30 => 'Digital Ad Sizes Needed',
                                    10 => 'If "other" above, please list the sizes needed',
                                    45 => '',
                                    13 => 'Who do you prefer to work on this project?',
                                    12 => 'Include any files or art pieces necessary',
                                    16 => 'File',
                                    18 => 'File',
                                    19 => 'File',
                                    11 => 'Project Instructions',
                                ),
                                'default_value' => false,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'allow_custom' => 0,
                                'search_placeholder' => '',
                                'parent_repeater' => 'field_630e72abaf029',
                            ),
                            array(
                                'key' => 'field_630e7f7b8a295',
                                'label' => 'Map To',
                                'name' => 'map_to',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'content' => 'Content',
                                    'description' => 'Description',
                                    'assignee_ids' => 'Assignee BaseCamp IDs',
                                    'completion_subscribers_ids' => 'Subscriber IDs',
                                    'notify' => 'Notify',
                                    'due_on' => 'Due On',
                                    'starts_on' => 'Starts On',
                                ),
                                'default_value' => false,
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'value',
                                'ajax' => 0,
                                'placeholder' => '',
                                'allow_custom' => 0,
                                'search_placeholder' => '',
                                'parent_repeater' => 'field_630e72abaf029',
                            ),
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'base-camp-link',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'left',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
                'acfe_display_title' => '',
                'acfe_autosync' => '',
                'acfe_form' => 0,
                'acfe_meta' => '',
                'acfe_note' => '',
            ));
            
            endif;
            
                
    }
    
}